# Generated by Django 4.1.7 on 2023-03-22 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_attendance_attendance_report"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="session_id",
            new_name="session_year_id",
        ),
    ]
